/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order_s;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import static java.awt.PageAttributes.MediaType.C;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

// new printing//
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;

/**
 *
 * @author pc
 */
public class Orders extends javax.swing.JFrame {
    /*resta*/
    double poso;
    double metrita;
    double resta;
    String operations;
    /*timokatalogos*/
    double souvlakia=1.30;
    double soutzoukakia=1.30;
    double psomi=0.50;
    double xoriatiki=3.00;
    double tzatziki=2.00;
    double portokalada=1.50;
    double cocacola=1.5;
    double beer=2.5;
    double retsina=3.0;
    double nero=0.50;
    double mono=2.5;
    double diplo=3.0;
  
    

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jnetprice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jqty1 = new javax.swing.JTextField();
        jpriceunit1 = new javax.swing.JTextField();
        jtotal1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jqty2 = new javax.swing.JTextField();
        jpriceunit2 = new javax.swing.JTextField();
        jtotal2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jqty3 = new javax.swing.JTextField();
        jpriceunit3 = new javax.swing.JTextField();
        jtotal3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jqty4 = new javax.swing.JTextField();
        jpriceunit4 = new javax.swing.JTextField();
        jtotal4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jqty5 = new javax.swing.JTextField();
        jpriceunit5 = new javax.swing.JTextField();
        jtotal5 = new javax.swing.JTextField();
        jtotal6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jqty7 = new javax.swing.JTextField();
        jpriceunit7 = new javax.swing.JTextField();
        jtotal7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jqty8 = new javax.swing.JTextField();
        jpriceunit8 = new javax.swing.JTextField();
        jtotal8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jqty9 = new javax.swing.JTextField();
        jpriceunit9 = new javax.swing.JTextField();
        jtotal9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jqty10 = new javax.swing.JTextField();
        jpriceunit10 = new javax.swing.JTextField();
        jtotal10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jqty11 = new javax.swing.JTextField();
        jpriceunit11 = new javax.swing.JTextField();
        jtotal11a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jqty12 = new javax.swing.JTextField();
        jpriceunit12 = new javax.swing.JTextField();
        jtotal12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jqty13 = new javax.swing.JTextField();
        jpriceunit13 = new javax.swing.JTextField();
        jtotal13 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        A = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ΕΚΔΗΛΩΣΕΙΣ ΠΡΟΦΗΤΗ ΗΛΙΑ ΠΟΝΤΙΑΚΟΥ ΠΟΛΙΤΙΣΤΙΚΟΥ ΣΥΛΛΟΓΟΥ ΧΩΡΥΓΙΟΥ 2019");
        setBackground(new java.awt.Color(153, 255, 255));
        setSize(new java.awt.Dimension(2000, 1000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setForeground(new java.awt.Color(255, 204, 51));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("ΣΥΝΟΛΟ:");

        jnetprice.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jnetprice.setText("0");

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton2.setText("ΣΥΝΟΛΟ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton3.setText("ΝΕΑ ΠΑΡΑΓΓΕΛΙΑ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton4.setText("ΕΞΟΔΟΣ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("ΕΚΤΥΠΩΣΗ ΑΠΟΔΕΙΞΗΣ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnetprice, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jnetprice)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(255, 204, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("ΕΙΔΟΣ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("ΤΕΜΑΧΙΑ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("ΤΙΜΗ ΜΟΝΑΔΑΣ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel20.setText("ΜΕΡΙΚΟ ΣΥΝΟΛΟ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("1. ΣΟΥΒΛΑΚΙΑ:");

        jqty1.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("2. ΣΟΥΤΖΟΥΚΑΚΙΑ:");

        jqty2.setText("0");

        jtotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("7. ΨΩΜΙ:");

        jqty3.setText("0");

        jtotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setText("5. ΧΩΡΙΑΤΙΚΗ:");

        jqty4.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("6. ΤΖΑΤΖΙΚΙ:");

        jqty5.setText("0");

        jtotal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal5ActionPerformed(evt);
            }
        });

        jtotal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("2.ΜΠΥΡΑ:");

        jqty7.setText("0");

        jtotal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal7ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 0));
        jLabel15.setText("1. ΡΕΤΣΙΝΑ:");

        jqty8.setText("0");

        jtotal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotal8ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 0));
        jLabel16.setText("3. ΣΑΝΤΟΥΙΤΣ ΜΟΝΟ:");

        jqty9.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("4. ΣΑΝΤΟΥΙΤΣ ΔΙΠΛΟ:");

        jqty10.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("ΠΟΤΑ");

        jLabel4.setBackground(new java.awt.Color(0, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaption);
        jLabel4.setText("ΦΑΓΗΤΑ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("3. COCA COLA:");

        jqty11.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("4. ΝΕΡΑ:");

        jqty12.setText("0");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("5. ΠΟΡΤΟΚΑΛΑΔΑ:");

        jqty13.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(163, 163, 163)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jqty1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(194, 194, 194))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jqty8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jpriceunit8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(jqty7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jpriceunit7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jpriceunit1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jpriceunit3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jqty9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jqty10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jqty4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jqty5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jqty3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(129, 129, 129))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(31, 31, 31)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jqty11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jqty12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jqty13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jpriceunit11, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                        .addComponent(jpriceunit12)
                                                        .addComponent(jpriceunit13, javax.swing.GroupLayout.Alignment.TRAILING))))
                                            .addGap(65, 65, 65))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(311, 429, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(311, 311, 311)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(311, 311, 311)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(404, 404, 404)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jtotal1)
                    .addComponent(jtotal2)
                    .addComponent(jtotal9)
                    .addComponent(jtotal10)
                    .addComponent(jtotal4)
                    .addComponent(jtotal5)
                    .addComponent(jtotal3)
                    .addComponent(jtotal7)
                    .addComponent(jtotal8)
                    .addComponent(jtotal6)
                    .addComponent(jtotal11a)
                    .addComponent(jtotal12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtotal13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(624, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jqty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpriceunit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jqty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpriceunit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtotal9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jqty9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpriceunit9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtotal10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jqty10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpriceunit10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jtotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jqty4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpriceunit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jtotal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jqty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpriceunit5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jqty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpriceunit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jqty8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpriceunit8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtotal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jqty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpriceunit7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtotal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jtotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtotal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jqty11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpriceunit11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtotal11a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jqty12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpriceunit12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtotal12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jqty13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpriceunit13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtotal13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel4)
                    .addContainerGap(388, Short.MAX_VALUE)))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTabbedPane1.setToolTipText("Bάζω Τελεία Όχι Κόμμα (,)");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(2);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ΑΠΟΔΕΙΞΗ", jPanel3);

        jPanel4.setToolTipText("Βάζω τελεία (.), ΟΧΙ ΚΟΜΜΑ(,)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("ΠΟΣΟ:");

        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("ΜΕΤΡΗΤΑ:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("ΡΕΣΤΑ:");

        C.setText("------------");

        jButton7.setText("ΥΠΟΛΟΓΙΣΜΟΣ ΡΕΣΤΑ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ΡΕΣΤΑ", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(145, 145, 145))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotal2ActionPerformed

    private void jtotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotal3ActionPerformed

    private void jtotal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotal5ActionPerformed

    private void jtotal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal6ActionPerformed
        double Qty1=Double.parseDouble(jqty1.getText());
        double Qty2=Double.parseDouble(jqty2.getText());
        double Qty3=Double.parseDouble(jqty3.getText());
        double Qty4=Double.parseDouble(jqty4.getText());
        double Qty5=Double.parseDouble(jqty5.getText());
        double Qty7=Double.parseDouble(jqty7.getText());
        double Qty8=Double.parseDouble(jqty8.getText());
        double Qty9=Double.parseDouble(jqty9.getText());
        double Qty10=Double.parseDouble(jqty10.getText());
        double Qty11=Double.parseDouble(jqty11.getText());
        double Qty12=Double.parseDouble(jqty12.getText());
        double Qty13=Double.parseDouble(jqty13.getText());
        int count=0;
        double total,subTotal,Addup,vTax,purchase1,purchase2,purchase3,purchase4,purchase5,purchase6,purchase7;
        double purchase8,purchase9,purchase10,purchase11,purchase12,purchase13;
        count=count+1;

        String souv_lakia=String.format("€%.2f",souvlakia);
        jpriceunit1.setText(souv_lakia);

        String sout_zoukakia=String.format("€%.2f",soutzoukakia);
        jpriceunit2.setText(sout_zoukakia);

        String ps_omi=String.format("€%.2f",psomi);
        jpriceunit3.setText(ps_omi);

        String ntomat_osalata=String.format("€%.2f",xoriatiki);
        jpriceunit4.setText(ntomat_osalata);

        String fe_ta=String.format("€%.2f",tzatziki);
        jpriceunit5.setText(fe_ta);
        
        String coca_cola=String.format("€%.2f",cocacola);
        jpriceunit11.setText(coca_cola);
        
        String portoka_lada=String.format("€%.2f",portokalada);
        jpriceunit13.setText(coca_cola);

        String be_er=String.format("€%.2f",beer);
        jpriceunit7.setText(be_er);

        String rets_ina=String.format("€%.2f",retsina);
        jpriceunit8.setText(rets_ina);

        String mo_no=String.format("€%.2f",mono);
        jpriceunit9.setText(mo_no);

        String poto_special1=String.format("€%.2f",diplo);
        jpriceunit10.setText(poto_special1);
        
        String ne_ro=String.format("€%.2f",nero);
        jpriceunit12.setText(ne_ro);
        
        

        purchase1=Qty1*souvlakia;
        purchase2=Qty2*soutzoukakia;
        purchase3=Qty3*psomi;
        purchase4=Qty4*xoriatiki;
        purchase5=Qty5*tzatziki;
        purchase7=Qty7*beer;
        purchase8=Qty8*retsina;
        purchase9=Qty9*mono;
        purchase10=Qty10*diplo;
        purchase11=Qty11*cocacola;
        purchase12=Qty12*nero;
        purchase13=Qty13*nero;
        String sub1=String.format("€%.2f",purchase1);
        jtotal1.setText(sub1);

        String sub2=String.format("€%.2f",purchase2);
        jtotal2.setText(sub2);

        String sub3=String.format("€%.2f",purchase3);
        jtotal3.setText(sub3);

        String sub4=String.format("€%.2f",purchase4);
        jtotal4.setText(sub4);

        String sub5=String.format("€%.2f",purchase5);
        jtotal5.setText(sub5);

        String sub7=String.format("€%.2f",purchase7);
        jtotal7.setText(sub7);

        String sub8=String.format("€%.2f",purchase8);
        jtotal8.setText(sub8);

        String sub9=String.format("€%.2f",purchase9);
        jtotal9.setText(sub9);

        String sub10=String.format("€%.2f",purchase10);
        jtotal10.setText(sub10);
        
        String sub11=String.format("€%.2f",purchase11);
        jtotal11a.setText(sub11);
        
        String sub12=String.format("€%.2f",purchase12);
        jtotal12.setText(sub12);
        
        String sub13=String.format("€%.2f",purchase13);
        jtotal13.setText(sub13);
              

        subTotal=purchase1+purchase2+purchase3+purchase4+purchase5+purchase7+purchase8+purchase9+purchase10+purchase11+purchase12+purchase13;

        String TotalAll=String.format("€%.2f",subTotal);
        
    }//GEN-LAST:event_jtotal6ActionPerformed

    private void jtotal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotal7ActionPerformed

    private void jtotal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotal8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotal8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double Qty1=Double.parseDouble(jqty1.getText());
        double Qty2=Double.parseDouble(jqty2.getText());
        double Qty3=Double.parseDouble(jqty3.getText());
        double Qty4=Double.parseDouble(jqty4.getText());
        double Qty5=Double.parseDouble(jqty5.getText());
        double Qty7=Double.parseDouble(jqty7.getText());
        double Qty8=Double.parseDouble(jqty8.getText());
        double Qty9=Double.parseDouble(jqty9.getText());
        double Qty10=Double.parseDouble(jqty10.getText());
        double Qty11=Double.parseDouble(jqty11.getText());
        double Qty12=Double.parseDouble(jqty12.getText());
        double Qty13=Double.parseDouble(jqty13.getText());
        jnetprice.setForeground(Color.red);
        int count=0;
        double total,subTotal,Addup,vTax,purchase1,purchase2,purchase3,purchase4,purchase5,purchase6,purchase7;
        double purchase8,purchase9,purchase10,purchase11,purchase12,purchase13;
        count=count+1;
        
        String souv_lakia=String.format("€%.2f",souvlakia);
        jpriceunit1.setText(souv_lakia);

        String sout_zoukakia=String.format("€%.2f",soutzoukakia);
        jpriceunit2.setText(sout_zoukakia);

        String ps_omi=String.format("€%.2f",psomi);
        jpriceunit3.setText(ps_omi);

        String xoriat_iki=String.format("€%.2f",xoriatiki);
        jpriceunit4.setText(xoriat_iki);

        String fe_ta=String.format("€%.2f",tzatziki);
        jpriceunit5.setText(fe_ta);

        String be_er=String.format("€%.2f",beer);
        jpriceunit7.setText(be_er);

        String rets_ina=String.format("€%.2f",retsina);
        jpriceunit8.setText(rets_ina);

        String poto_aplo1=String.format("€%.2f",mono);
        jpriceunit9.setText(poto_aplo1);

        String di_plo=String.format("€%.2f",diplo);
        jpriceunit10.setText(di_plo);
        
        String coca_cola=String.format("€%.2f",cocacola);
        jpriceunit11.setText(coca_cola);
        
        String ne_ra=String.format("€%.2f",nero);
        jpriceunit12.setText(ne_ra);
        
        String portoka_lada=String.format("€%.2f",portokalada);
        jpriceunit13.setText(portoka_lada);

        purchase1=Qty1*souvlakia;
        purchase2=Qty2*soutzoukakia;
        purchase3=Qty3*psomi;
        purchase4=Qty4*xoriatiki;
        purchase5=Qty5*tzatziki;
        purchase7=Qty7*beer;
        purchase8=Qty8*retsina;
        purchase9=Qty9*mono;
        purchase10=Qty10*diplo;
        purchase11=Qty11*cocacola;
        purchase12=Qty12*nero;
        purchase13=Qty13*portokalada;
        

        String sub1=String.format("€%.2f",purchase1);
        jtotal1.setText(sub1);

        String sub2=String.format("€%.2f",purchase2);
        jtotal2.setText(sub2);

        String sub3=String.format("€%.2f",purchase3);
        jtotal3.setText(sub3);

        String sub4=String.format("€%.2f",purchase4);
        jtotal4.setText(sub4);

        String sub5=String.format("€%.2f",purchase5);
        jtotal5.setText(sub5);

        String sub7=String.format("€%.2f",purchase7);
        jtotal7.setText(sub7);

        String sub8=String.format("€%.2f",purchase8);
        jtotal8.setText(sub8);

        String sub9=String.format("€%.2f",purchase9);
        jtotal9.setText(sub9);

        String sub10=String.format("€%.2f",purchase10);
        jtotal10.setText(sub10);
        
        String sub11=String.format("€%.2f",purchase11);
        jtotal11a.setText(sub11);
        
        String sub12=String.format("€%.2f",purchase12);
        jtotal12.setText(sub12);
        
         String sub13=String.format("€%.2f",purchase13);
        jtotal13.setText(sub13);

        subTotal=purchase1+purchase2+purchase3+purchase4+purchase5+purchase7+purchase8+purchase9+purchase10+purchase11+purchase12+purchase13;

        String TotalAll=String.format("€ %.2f",subTotal);
        jnetprice.setText(TotalAll);
        String Poso=String.format("%.2f",subTotal);
        double value=Double.parseDouble(Poso.replace(",","."));
        String value1=String.format("%.2f",value);
        A.setText(value1);
        
        //ΕΜΦΑΝΙΣΗ ΑΠΟΔΕΙΞΗΣ
        int Qty1a=Integer.parseInt(jqty1.getText());
        int Qty2a=Integer.parseInt(jqty2.getText());
        int Qty3a=Integer.parseInt(jqty3.getText());
        int Qty4a=Integer.parseInt(jqty4.getText());
        int Qty5a=Integer.parseInt(jqty5.getText());
        int Qty7a=Integer.parseInt(jqty7.getText());
        int Qty8a=Integer.parseInt(jqty8.getText());
        int Qty9a=Integer.parseInt(jqty9.getText());
        int Qty10a=Integer.parseInt(jqty10.getText());
        int Qty11a=Integer.parseInt(jqty11.getText());
        int Qty12a=Integer.parseInt(jqty12.getText());
        int Qty13a=Integer.parseInt(jqty13.getText());
        try {
            //double P=Double.valueOf(A.getText());
            //double M=Double.valueOf(B.getText());
            NumberFormat format = NumberFormat.getInstance(Locale.FRANCE);
            
            String test=A.getText();
            test = test.replace(".",",");
            Number number = format.parse(test);
            double doublet= number.doubleValue();
            
            double R=doublet;
            String Resta=String.format("€ %.2f",R);
            jTextArea1.append("\n\n\n");
        jTextArea1.append("**ΝΕΑ ΠΑΡΑΓΓΕΛΙΑ**\n\n");
        jTextArea1.append("          ΦΑΓΗΤΑ:\n\n");
               if (Qty1a!=0)
                 jTextArea1.append("ΣΟΥΒΛΑΚΙΑ\t\t\t"+Qty1a+"\n");
               if (Qty2a!=0)
                 jTextArea1.append("ΣΟΥΤΖΟΥΚΑΚΙΑ\t"+Qty2a+"\n");
               if (Qty9a!=0)
                 jTextArea1.append("ΜΟΝΑ ΣΑΝΤ.\t\t"+Qty9a+"\n");
               if (Qty10a!=0)
                 jTextArea1.append("ΔΙΠΛΑ ΣΑΝΤ.\t\t"+Qty10a+"\n");
               if (Qty3a!=0)
                 jTextArea1.append("ΜΕΡΙΔΕΣ ΨΩΜΙ\t\t"+Qty3a+"\n");
               if (Qty4a!=0)
                 jTextArea1.append("ΧΩΡΙΑΤΙΚΕΣ\t\t\t"+Qty4a+"\n");
               if (Qty5a!=0)
                 jTextArea1.append("ΤΖΑΤΖΙΚΙΑ\t\t\t"+Qty5a+"\n");
               jTextArea1.append("\n\n\n\n\n");
               jTextArea1.append("**************************\n");
               jTextArea1.append("         ΠΟΤΑ:\n\n");
               if (Qty7a!=0)
                 jTextArea1.append("ΜΠΥΡΕΣ\t\t\t\t"+Qty7a+"\n");
               if (Qty8a!=0)
                 jTextArea1.append("ΡΕΤΣΙΝΕΣ\t\t\t"+Qty8a+"\n");
               if (Qty11a!=0)
                 jTextArea1.append("COCA COLA\t\t"+Qty11a+"\n");
               if (Qty12a!=0)
                 jTextArea1.append("ΝΕΡΑ\t\t\t\t\t"+Qty12a+"\n");
               if (Qty13a!=0)
                 jTextArea1.append("ΠΟΡΤΟΚΑΛΑΔΕΣ\t\t\t\t\t"+Qty13a+"\n");
               jTextArea1.append("------------------------------\n");
               
               jTextArea1.append("ΤΕΛΙΚΟ ΠΟΣΟ: "+R+"€\n");
               jTextArea1.append("\n\n");
               jTextArea1.append("ΕΥΧΑΡΙΣΤΟΥΜΕ ΠΟΛΥ!\n");
               jTextArea1.append("\n\n"
                       + "ΠΟΝΤΙΑΚΟΣ ΠΟΛ/ΚΟΣ\nΣΥΛΛΟΓΟΣ ΧΩΡΥΓΙΟΥ\n\n"
               +" Designed by \n"+"George Karamousalidis");
           
        } catch (ParseException ex) {
            Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText(null);
        jqty1.setText("0");
        jqty2.setText("0");
        jqty3.setText("0");
        jqty4.setText("0");
        jqty5.setText("0");
        jqty7.setText("0");
        jqty8.setText("0");
        jqty9.setText("0");
        jqty10.setText("0");
        jqty11.setText("0");
        jqty12.setText("0");
        jqty13.setText("0");

        jnetprice.setText("0");
        A.setText("0");
        B.setText("0");
        C.setText("0");
        
        jpriceunit1.setText(null);
        jpriceunit2.setText(null);
        jpriceunit3.setText(null);
        jpriceunit4.setText(null);
        jpriceunit5.setText(null);
        jpriceunit7.setText(null);
        jpriceunit8.setText(null);
        jpriceunit9.setText(null);
        jpriceunit10.setText(null);
        jpriceunit11.setText(null);
        jpriceunit12.setText(null);
        jpriceunit13.setText(null);
        jtotal1.setText(null);
        jtotal2.setText(null);
        jtotal3.setText(null);
        jtotal4.setText(null);
        jtotal5.setText(null);
        jtotal6.setText(null);
        jtotal7.setText(null);
        jtotal8.setText(null);
        jtotal9.setText(null);
        jtotal10.setText(null);
        jtotal11a.setText(null);
        jtotal12.setText(null);
        jtotal13.setText(null);
         

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            this.getContentPane().setBackground(Color.YELLOW);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    
        
        try {
            Boolean ppt=jTextArea1.print();
            if (ppt){
                JOptionPane.showMessageDialog(null,"Done");
            }
            else{
                JOptionPane.showMessageDialog(null,"Printing...");
                
            }
        } catch (PrinterException ex) {
            Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            //double P=Double.valueOf(A.getText());
            //double M=Double.valueOf(B.getText());
            NumberFormat format = NumberFormat.getInstance(Locale.FRANCE);
            
            String test=A.getText();
            test = test.replace(".",",");
            Number number = format.parse(test);
            double doublet= number.doubleValue();
            
           
            String test1=B.getText();
            test1 = test1.replace(".",",");
            Number number1 = format.parse(test1);
            double doublet1=number1.doubleValue();

            
            double R=doublet1-doublet;
            String Resta=String.format("€ %.2f",R);
            C.setText(Resta);
        } catch (ParseException ex) {
            Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JLabel C;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jnetprice;
    private javax.swing.JTextField jpriceunit1;
    private javax.swing.JTextField jpriceunit10;
    private javax.swing.JTextField jpriceunit11;
    private javax.swing.JTextField jpriceunit12;
    private javax.swing.JTextField jpriceunit13;
    private javax.swing.JTextField jpriceunit2;
    private javax.swing.JTextField jpriceunit3;
    private javax.swing.JTextField jpriceunit4;
    private javax.swing.JTextField jpriceunit5;
    private javax.swing.JTextField jpriceunit7;
    private javax.swing.JTextField jpriceunit8;
    private javax.swing.JTextField jpriceunit9;
    private javax.swing.JTextField jqty1;
    private javax.swing.JTextField jqty10;
    private javax.swing.JTextField jqty11;
    private javax.swing.JTextField jqty12;
    private javax.swing.JTextField jqty13;
    private javax.swing.JTextField jqty2;
    private javax.swing.JTextField jqty3;
    private javax.swing.JTextField jqty4;
    private javax.swing.JTextField jqty5;
    private javax.swing.JTextField jqty7;
    private javax.swing.JTextField jqty8;
    private javax.swing.JTextField jqty9;
    private javax.swing.JTextField jtotal1;
    private javax.swing.JTextField jtotal10;
    private javax.swing.JTextField jtotal11a;
    private javax.swing.JTextField jtotal12;
    private javax.swing.JTextField jtotal13;
    private javax.swing.JTextField jtotal2;
    private javax.swing.JTextField jtotal3;
    private javax.swing.JTextField jtotal4;
    private javax.swing.JTextField jtotal5;
    private javax.swing.JTextField jtotal6;
    private javax.swing.JTextField jtotal7;
    private javax.swing.JTextField jtotal8;
    private javax.swing.JTextField jtotal9;
    // End of variables declaration//GEN-END:variables

    private void printText(PrintJob myJob, Graphics g, String s) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
